development: &pgsql
  adapter: postgresql
  database: msf
  username: msf
  password: p2CAL8HDqICvJDcAYsMGWOWwEZi2zF2bhp3YHD8fRdU=
  host: 127.0.0.1
  port: 5433
  pool: 200

production: &production
  <<: *pgsql

test:
  <<: *pgsql
  database: msftest
  username: msftest
  password: NbKcjr1sFkRrtiMCWJYNQESk+hSZSidvCvxydcqSmaw=
